# Change these first
owner: kllukk # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: WWW
    url: https://ondrejaugusta.cz
  - name: Minecraft
    url: http://play.ondrejaugusta.cz:8123

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ondrejaugusta.cz
  # baseUrl: /your-repo-name
  logoUrl: https://ondrejaugusta.cz/img/eye.svg
  name: Stav služeb
  introTitle: "Stav služeb"
  introMessage: Něco nefunguje? A myslíte, že to fungovat má? Podívejte se na stav služeb!
  navbar:
    - title: Stav
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
